
package com.concretepage.site_connect;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SiteConnectService", targetNamespace = "https://cmtpi.siteminder.com:443/siteconnect", wsdlLocation = "https://cmtpi.siteminder.com/siteconnect/services/siteconnect_v1.1.0_inlined.wsdl")
public class SiteConnectService_Service
    extends Service
{

    private final static URL SITECONNECTSERVICE_WSDL_LOCATION;
    private final static WebServiceException SITECONNECTSERVICE_EXCEPTION;
    private final static QName SITECONNECTSERVICE_QNAME = new QName("https://cmtpi.siteminder.com:443/siteconnect", "SiteConnectService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://cmtpi.siteminder.com/siteconnect/services/siteconnect_v1.1.0_inlined.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SITECONNECTSERVICE_WSDL_LOCATION = url;
        SITECONNECTSERVICE_EXCEPTION = e;
    }

    public SiteConnectService_Service() {
        super(__getWsdlLocation(), SITECONNECTSERVICE_QNAME);
    }

    public SiteConnectService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SITECONNECTSERVICE_QNAME, features);
    }

    public SiteConnectService_Service(URL wsdlLocation) {
        super(wsdlLocation, SITECONNECTSERVICE_QNAME);
    }

    public SiteConnectService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SITECONNECTSERVICE_QNAME, features);
    }

    public SiteConnectService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SiteConnectService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SiteConnectService
     */
    @WebEndpoint(name = "SiteConnectServicePort")
    public SiteConnectService getSiteConnectServicePort() {
        return super.getPort(new QName("https://cmtpi.siteminder.com:443/siteconnect", "SiteConnectServicePort"), SiteConnectService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SiteConnectService
     */
    @WebEndpoint(name = "SiteConnectServicePort")
    public SiteConnectService getSiteConnectServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("https://cmtpi.siteminder.com:443/siteconnect", "SiteConnectServicePort"), SiteConnectService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SITECONNECTSERVICE_EXCEPTION!= null) {
            throw SITECONNECTSERVICE_EXCEPTION;
        }
        return SITECONNECTSERVICE_WSDL_LOCATION;
    }

}
